//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiltroFechasVideo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblContrato
    {
        public int idContrato { get; set; }
        [Display(Name = "Nombre")]
        public int idCliente { get; set; }
        [Display(Name = "Monto de Contrato")]
        public decimal montoContrato { get; set; }
        [Display(Name = "Fecha de Contrato")]
        [DataType(DataType.Date)]
        public System.DateTime fechaContrato { get; set; }
    
        public virtual tblCliente tblCliente { get; set; }
    }
}
